### ISSUE TITLE
Augustus conversion failing

### ISSUE THREAD

**Issue by jorvis** [jorvis/biocode#51]
User @kayussky911 reports:

convert_augustus_to_gff3.py -i augustus_erins.gtf -o new_augustus

my input looks like,

scaffold10x_1 AUGUSTUS gene 3591 4530 0.27 - . g1
scaffold10x_1 AUGUSTUS transcript 3591 4530 0.27 - . g1.t1
scaffold10x_1 AUGUSTUS stop_codon 3591 3593 . - 0 transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS CDS 3591 3859 0.34 - 2 transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS exon 3591 3859 . - . transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS intron 3860 4022 0.28 - . transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS CDS 4023 4530 0.63 - 0 transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS exon 4023 4530 . - . transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS start_codon 4528 4530 . - 0 transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1 AUGUSTUS gene 26186 31433 0.2 - . g2
scaffold10x_1 AUGUSTUS transcript 26186 31433 0.2 - . g2.t1
scaffold10x_1 AUGUSTUS stop_codon 26186 26188 . - 0 transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS CDS 26186 26304 0.37 - 2 transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS exon 26186 26304 . - . transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS intron 26305 29389 0.28 - . transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS CDS 29390 30220 0.39 - 2 transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS exon 29390 30220 . - . transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS intron 30221 30844 0.45 - . transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS CDS 30845 31433 0.41 - 0 transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1 AUGUSTUS exon 30845 31433 . - . transcript_id "g2.t1"; gene_id "g2";

the output just says;

##gff-version 3

and that's it. so I think its the last columns of the input files I need to work on.

**Comment by kayussky911** [comment]
Regarding the version of Augustus,  the file was generated using braker, the AUGUSTUS version should be  augustus-3.2.3, although I have augustus.2.5.5 in my environment.

**Comment by jorvis** [comment]
When you ran Augustus, did you tell it to output GFF?  By default its output is GTF.  The important option is:

```
--gff3=on/off
  output in gff3 format
```

[Source](http://augustus.gobics.de/binaries/README.TXT)

**Comment by kayussky911** [comment]
thanks Jorvis 

I would repeat the augustus analysis.

**Comment by jorvis** [comment]
Leaving this open so the script can be modified to support either format
from Augustus

**Comment by Kapeel** [comment]
Hi, I used the example gtf in the script convert_augustus_to_gff3.py. I get the below error:
```
convert_augustus_to_gff3.py -i test.gtf -o test.gff3
Traceback (most recent call last):
  File "/Users/kchougul/development/anaconda3/bin/convert_augustus_to_gff3.py", line 189, in <module>
    main()
  File "/Users/kchougul/development/anaconda3/bin/convert_augustus_to_gff3.py", line 91, in main
    gene.print_as(fh=fout, source='AUGUSTUS', format='gff3')
AttributeError: 'NoneType' object has no attribute 'print_as'
```
