### ISSUE TITLE
Biocode.gff module error

### ISSUE THREAD

**Issue by PlantDr430** [jorvis/biocode#58]
Hello,

I kept getting an error that the module biocode.gff doesn't contain the function "column_9_value" even though I checked the module and I see that the function exists.

```
stephenwyka@bspmgenomics:/data/wyka/funannotate/LM470$ python3 /data/wyka/biocode/gff/convert_glimmerHMM_gff_to_gff3.py -i LM470_glimmerhmm.gff -o LM470_glimmerhmm.gff3
Traceback (most recent call last):
  File "/data/wyka/biocode/gff/convert_glimmerHMM_gff_to_gff3.py", line 104, in <module>
    main()
  File "/data/wyka/biocode/gff/convert_glimmerHMM_gff_to_gff3.py", line 66, in main
    id = gff.column_9_value(cols[8], 'ID')
AttributeError: module 'biocode.gff' has no attribute 'column_9_value'
stephenwyka@bspmgenomics:/data/wyka/funannotate/LM470$
```

**Comment by jorvis** [comment]
I see that you closed this, is there actually no issue here?

**Comment by PlantDr430** [comment]
Yea, after I put up the issue. I realized I had set the wrong path for the
module. Sorry about that.
