### ISSUE TITLE
AttributeError: type object 'str' has no attribute 'maketrans'

### ISSUE THREAD

**Issue by PengXieAMJ** [jorvis/biocode#61]
Traceback (most recent call last):
  File "remove_duplicate_sequences.py", line 27, in <module>
    from biocode import utils
  File "/opt/biocode/lib/biocode/utils.py", line 6, in <module>
    _nt_comp_table = bytes.maketrans(b'ACBDGHKMNSRUTWVYacbdghkmnsrutwvy', \
AttributeError: type object 'str' has no attribute 'maketrans'

**Comment by PengXieAMJ** [comment]
Kindly ask for help!

**Comment by jorvis** [comment]
Try running the script with Python3 instead of Python2.
