### ISSUE TITLE
Formatting Issue?

### ISSUE THREAD

**Issue by remiketchum** [jorvis/biocode#72]
Hi,

I am currently trying to convert a gtf or gff3 file output from Augustus to a format that will be read by PASA. However, when I try to run this command:

convert_augustus_to_gff3.py -i augustus.hints.gtf  -o test.gff3 

I consistently get an error code like this one:

  File "/users/rketchu1/.local/bin/convert_augustus_to_gff3.py", line 133, in main
    raise Exception("ERROR: GTF detected but gene row has bad 9th column format: {0}".format(cols[8]))
Exception: ERROR: GTF detected but gene row has bad 9th column format: jg33035

I have rerun Augustus with the -gff3 flag and tried to run the same command pasted above on the gff3 file but the following error:

Traceback (most recent call last):
  File "/users/rketchu1/.local/bin/convert_augustus_to_gff3.py", line 189, in <module>
    main()
  File "/users/rketchu1/.local/bin/convert_augustus_to_gff3.py", line 173, in main
    raise Exception("ERROR: Found CDS column with parent ({0}) mRNA not yet in the file".format(parent_id))
Exception: ERROR: Found CDS column with parent (jg33035.t1) mRNA not yet in the file

I'm not entirely sure what is wrong with the file formatting. I am running Augustus 3.4.0  through Braker 2.1.5.

**Comment by jorvis** [comment]
Hmm, in the documentation of the convert_augustus_to_gff3.py script it has an example gene block from Augustus.  Can you see how yours compares with that structure?  Maybe it has been updated.  Regarding the 2nd error, after you've used the -gff3 flag, it seems the features are out of order with some being referenced before they are actually defined.  This may be another augustus issue but possibly corrected with this script:

biocode/gff/correct_gff_feature_order.pl

Could you possibly copy/paste a block representing an entire gene's rows here into the ticket?
