### ISSUE TITLE
Issue with convert prodigal output to standard GFF3

### ISSUE THREAD

**Issue by jjuradoc** [jorvis/biocode#83]
Hi, 

I want to convert the Prodigal output to standard GFF3 using the command: convert_prodigal_to_gff3.py -i unit2_new_genome.prodigal.gff -o unit2_new_genome.prodigal.gff3

I obtain this error message:

Traceback (most recent call last):
  File "/home/jjuradoc/class/myenv/bin/convert_prodigal_to_gff3.py", line 66, in <module>
    main()
  File "/home/jjuradoc/class/myenv/bin/convert_prodigal_to_gff3.py", line 53, in main
    id, annotation = m.groups()
                     ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'groups'

What can I do in this case? thank you in advance

**Comment by jorvis** [comment]
Do you think you could attach your input file here?

**Comment by jjuradoc** [comment]
Hi Joshua,

Thank you for replying to my message. Please find attached a screenshot of the message I got and of the input file. Thank you.

Sincerely,

Juan Jurado


[Email signature image for Schulich]
Juan Jurado-Coronel
MSc in Biotechnology, BSc in Biology
PhD in Neuroscience Student - Duennwald Lab

University of Western Ontario

MSB415 (Lab)

London, ON, Canada, N6A 5C1

E-mail: ***@***.***

________________________________
De: Joshua Orvis ***@***.***>
Enviado: domingo, 20 de octubre de 2024 20:41
Para: jorvis/biocode ***@***.***>
Cc: Juan Jurado Coronel ***@***.***>; Author ***@***.***>
Asunto: Re: [jorvis/biocode] Issue with convert prodigal output to standard GFF3 (Issue #83)

No suele recibir correo electrónico de ***@***.*** Por qué es esto importante<https://aka.ms/LearnAboutSenderIdentification>

Do you think you could attach your input file here?

**Comment by jorvis** [comment]
Juan -

I don't believe you can attach something when replying to the issue via e-mail.  Could you please try again using GitHub in your browser?

**Comment by jjuradoc** [comment]
HI Joshua, sorry for that.

Please find attached the files here.
![Screenshot](https://github.com/user-attachments/assets/7ef628a8-dd0c-4551-a934-8aca54275b07)
[convert_prodigal_to_gff3.py.txt](https://github.com/user-attachments/files/17481301/convert_prodigal_to_gff3.py.txt)

**Comment by jorvis** [comment]
It seems you attached the python script itself and what I needed was the input file that Prodigal produced.  Making a note here, but I have a few students this semester which are having the same issue, so I can get a file from one of them.
